title: Scott Mason
description: Postdoctoral Researcher, NYU Courant (Mathematics)
theme: minima
markdown: kramdown
url: https://USERNAME.github.io
author:
  name: Scott Mason
  email: your.email@nyu.edu
# Pages to show in the top navigation
header_pages:
  - publications.md
  - teaching.md
  - talks.md
# If you later move pages into a folder like _pages/, add:
# include: [_pages]
# And change header_pages entries accordingly.
