title: Scott Mason
description: Postdoctoral Researcher, NYU Courant (Mathematics)
theme: minima
markdown: kramdown
url: https://scottmason-math.github.io
author: Scott Mason
email: sm12814@nyu.edu
# Pages to show in the top navigation
header_pages:
  - publications.md
  - teaching.md
  - talks.md
# If you later move pages into a folder like _pages/, add:
# include: [_pages]
# And change header_pages entries accordingly.
